apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-engine
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-engine
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-engine
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-engine
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: engine
          image: "{{ .Values.engine.image.repository }}:{{ .Values.engine.image.tag }}"
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.engine.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.engine.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.engine.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            # Database configuration
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgres
            - name: POSTGRES_PORT
              value: {{ .Values.postgres.service.port | quote }}
            - name: POSTGRES_SSLMODE
              value: "disable"
            # Redis cache configuration
            - name: REDIS_HOST
              value: {{ .Release.Name }}-redis
            - name: REDIS_PORT
              value: {{ .Values.redis.service.port | quote }}
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_DB
              value: "0"
          volumeMounts:
            - name: config-volume
              mountPath: /bin/engine.yaml
              subPath: engine.yaml
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-engine-config 